### ISSUE TITLE
Compile issue on Debian 10

### ISSUE THREAD

**Issue by mirfan899** [alumae/gst-kaldi-nnet2-online#99]
I tried to compile gst on Debian 10 with latest Kaldi and it throws this error
```shell
root@freeswitch:~/tools/gst-kaldi-nnet2-online/src# KALDI_ROOT=/root/kaldi/ make
Makefile:75: warning: overriding recipe for target 'clean'
/root/kaldi//src/makefiles/default_rules.mk:85: warning: ignoring old recipe for target 'clean'
Makefile:79: warning: overriding recipe for target 'depend'
/root/kaldi//src/makefiles/default_rules.mk:149: warning: ignoring old recipe for target 'depend'
g++ -std=c++11 -I.. -isystem /root/kaldi/tools/openfst-1.6.7/include -O1 -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Wno-deprecated-declarations -Winit-self -DKALDI_DOUBLEPRECISION=0 -DHAVE_EXECINFO_H=1 -DHAVE_CXXABI_H -DHAVE_MKL -I/opt/intel/mkl/include -m64 -msse -msse2 -pthread -g -fPIC -DHAVE_SPEEX -I/root/kaldi/src/../tools/speex/include -I/root/kaldi//src   -c -o gstkaldinnet2onlinedecoder.o gstkaldinnet2onlinedecoder.cc
gstkaldinnet2onlinedecoder.cc: In function ‘void kaldi::gst_kaldinnet2onlinedecoder_reset_cmvn_state(kaldi::Gstkaldinnet2onlinedecoder*)’:
gstkaldinnet2onlinedecoder.cc:2082:29: error: ‘struct kaldi::OnlineNnet2FeaturePipelineInfo’ has no member named ‘global_cmvn_stats_rxfilename’; did you mean ‘global_cmvn_stats’?
   if (filter->feature_info->global_cmvn_stats_rxfilename != "")
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                             global_cmvn_stats
gstkaldinnet2onlinedecoder.cc:2083:45: error: ‘struct kaldi::OnlineNnet2FeaturePipelineInfo’ has no member named ‘global_cmvn_stats_rxfilename’; did you mean ‘global_cmvn_stats’?
       ReadKaldiObject(filter->feature_info->global_cmvn_stats_rxfilename,
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                             global_cmvn_stats
make: *** [<builtin>: gstkaldinnet2onlinedecoder.o] Error 1
```

**Comment by alumae** [comment]
Thanks. I think it is due to a recent breaking change in Kaldi.

**Comment by BaderEddineB** [comment]
Hello !

I have the same error, i use debian 10 !
How can we fix it ?

**Comment by jonasschui** [comment]
Same error in issue 25 when using databricks/runtime:latest within docker build

**Comment by BaderEddineB** [comment]
this problem related to the new version of kaldi 5.5.8
the plugin works well with version 5.5.7
here is the link for the download:
https://github.com/kaldi-asr/kaldi/tree/84a6efbdddd9299f3192d1e3b26d6968c8e1a6ab

**Comment by alumae** [comment]
I think I fixed it but I my time is really tight at the moment so I was not really able to fix it. Please reopen if it doesn't work.
